export default {
  // Auth / user
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SET_USER: 'SET_USER',
  GET_USER: 'GET_USER',
  SET_CONTACTS: 'SET_CONTACTS',

  // chat per user data
  SET_CHAT: 'SET_CHAT',
  SET_CHAT_ID: 'SET_CHAT_ID',

  // Articles belongs to user.
  SET_USER_ARTICLES: 'SET_USER_ARTICLES',

  // Article
  UPLOAD_ARTICLE: 'ADD_ARTICLE',
  UPDATE_UPLOAD_ARTICLE: 'UPDATE_UPLOAD_ARTICLE',
  CLEAR_UPLOAD_ARTICLE: 'CLEAR_ARTICLE',
  SET_ARTICLES: 'SET_ARTICLES',
  UPDATE_ARTICLES: 'UPDATE_ARTICLES',
  SET_ARTICLE_LIMIT: 'SET_ARTICLE_LIMIT',
  SET_LAST_ARTICLE: 'SET_LAST_ARTICLE',
};
